# Generated by Django 5.1 on 2026-03-26 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_course_subject_coursesubject_attendance_marks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_marks', models.FloatField()),
                ('max_marks', models.FloatField(default=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.coursesubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
        ),
    ]
